name: psp_medprep
description: PSP‑MedPrep Android App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # PDF handling
  pdfx: ^2.9.2

  # State management
  provider: ^7.0.0

  # HTTP requests
  http: ^1.0.0

  # Launch URLs
  url_launcher: ^6.3.2

  # Show toast messages
  fluttertoast: ^9.0.0

  # Screen size adaptation
  flutter_screenutil: ^5.9.3

  # Network connectivity check
  connectivity_plus: ^4.0.0

  # Share content via Android share menu
  share_plus: ^6.0.0

  # Local notifications
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/papers/
    - assets/notes/
    - assets/mock_tests/
